### ISSUE TITLE
Email assistant roadmap

### ISSUE THREAD

**Issue by qertis** [gotois/ProstoDiary_bot#606]
- [ ] Пользователь через oidc добавляет считыватель почтового ассистента. 
- [ ] Пользователь сам делает forward определенного письма или пишет письмо сам ассистенту на его почту
- [ ] CRON делает проверку всех писем раз в сутки
- [ ] Ассистент присылает письмо с форматом
- [ ] Пользователь добавляет уведомления в свой календарь
